### ISSUE TITLE
Test with keycloak-kibana

### ISSUE THREAD

**Issue by SCadilhac** [novomatic-tech/elasticsearch-proxy#5]
Hello,

I've tried to start your nice work here along with [keycloak-kibana](https://github.com/novomatic-tech/keycloak-kibana), and I'm seeing the following:

- At start time it seems that Kibana attempts a `HEAD /` request to ES. As this request has no `Authorization` header, it fails on the proxy side, with error _The authentication for the HEAD / was not attempted_.
- If I manually run a `curl -X HEAD http://proxy:19200 -vvv -H 'Authorization: abcdef'`, I can see the request being passed to ES, and replied, but the reply doesn't come back to curl, which eventually times out.

```
bash-4.2$ curl -XHEAD http://proxy:19200 -vvv -H 'Authorization: abcdef'
* About to connect() to proxy port 19200 (#0)
*   Trying 172.19.0.2...
* Connected to proxy (172.19.0.2) port 19200 (#0)
> HEAD / HTTP/1.1
> User-Agent: curl/7.29.0
> Host: proxy:19200
> Accept: */*
> Authorization: abcdef
>
< HTTP/1.1 200
< Content-Type: application/json;charset=UTF-8
< Content-Length: 500
< Date: Wed, 05 Jun 2019 10:34:13 GMT
<
* transfer closed with 500 bytes remaining to read
* Closing connection 0
curl: (18) transfer closed with 500 bytes remaining to read
```

Am I missing something? I've not diggen into the the code.
Thanks!

**Comment by tomnocon** [comment]
Hello @SCadilhac 
you have to configure basic authentication for kibana. Example:
```
elasticsearch.hosts: http://elasticsearch-proxy:19200
elasticsearch.username: admin
elasticsearch.password: admin
```
By default all requests with basic authentication are forwarded to the elasticsearch without filtering.

**Comment by tomnocon** [comment]
I'm closing this issue. Feel free to give us further feedback.

**Comment by SCadilhac** [comment]
Hi @tomnocon 
Thank you! I just tried and indeed basic authentication makes Kibana start fine. At the moment I don't think the proxy is properly retrieving the attributes from Keycloak in my setup, I'm now investigating more on this part.
